import { readFileSync } from 'fs';
import { resolve } from 'path';
import { runInNewContext } from 'vm';

const legacy = (library: string, text = '<p>Description</p>') => ({
  library, params: { text }, subContentId: 'child-uuid', metadata: { title: 'Description' },
});
const loadUpgrade = () => {
  const context: any = {};
  // H5P upgrades may run in a worker: no document, window, H5P, or child libraries.
  runInNewContext(readFileSync(resolve(__dirname, '../../upgrades.js'), 'utf8'), context);
  return context.H5PUpgrades['H5P.NDLATimelinePapiJo'][1][2];
};
const convertPapiJo = (text: string) => {
  const parameters = { titleSlide: { description: legacy('H5P.AdvancedTextPapiJo 1.2', text) } };
  const finished = jest.fn();
  loadUpgrade()(parameters, finished);
  expect(finished).toHaveBeenCalledWith(null, parameters);
  return parameters.titleSlide.description;
};

describe('staged description content upgrade', () => {
  it('ships the standalone upgrade matching its template and HTML5 entity data', () => {
    const template = readFileSync(resolve(__dirname, 'description-upgrades.template.js'), 'utf8');
    const entities = JSON.parse(readFileSync(resolve(__dirname, 'html-entities.json'), 'utf8'));
    expect(readFileSync(resolve(__dirname, '../../upgrades.js'), 'utf8')).toBe(
      '// Generated by npm run build:upgrades. Edit the template, not this file.\n' +
      template.replace('/* HTML_ENTITIES */ {}', JSON.stringify(entities)),
    );
  });

  it.each(['H5P.AdvancedText 1.1', 'H5P.AdvancedText 1.1.9'])(
    'preserves %s HTML exactly on title and all event modes', (library) => {
      const html = '<h3>Titre é</h3><p style="color: #ff0000;">A <strong>word</strong> &amp; ' +
        '<a href="https://example.com">link</a></p>\n<table><tr><td>Cell</td></tr></table>';
      const parameters = {
        showTitleSlide: false, titleSlide: { description: legacy(library, html), title: 'Title' },
        timelineItems: ['text', 'image', 'none'].map((mode) => ({
          description: legacy(library, html), TextOrImage: mode,
          descriptionImage: { path: 'images/description.png' },
        })), behaviour: { scalingMode: 'index' },
      };
      const finished = jest.fn();
      loadUpgrade()(parameters, finished);
      expect(finished).toHaveBeenCalledWith(null, parameters);
      expect(parameters.titleSlide.description).toBe(html);
      parameters.timelineItems.forEach((slide) => {
        expect(slide.description).toBe(html);
        expect(slide.descriptionImage.path).toBe('images/description.png');
      });
      expect(parameters.behaviour).toEqual({ scalingMode: 'index' });
      expect(parameters.titleSlide.title).toBe('Title');
    },
  );

  it.each(['H5P.AdvancedTextPapiJo 1.2', 'H5P.AdvancedTextPapiJo 1.2.4'])(
    'converts %s to raw text and discards all child data', (library) => {
      const parameters = { titleSlide: { description: {
        ...legacy(library), params: {
          text: '<p>Hello <strong>world</strong>. <span class="papijo-tooltip" ' +
            'data-papijo-tooltip="<p>Explanation</p>" data-papijo-tooltip-id="abc">word</span></p>',
          tooltipImages: [{ id: 'abc', image: { path: 'images/tip.png' }, alt: 'Diagram' }],
          tooltipDefinitions: { abc: 'Definition' }, futureParameter: { anything: true },
        },
      } } };
      const finished = jest.fn();
      loadUpgrade()(parameters, finished);
      expect(finished).toHaveBeenCalledWith(null, parameters);
      expect(parameters.titleSlide.description).toBe('Hello world. word');
      expect(JSON.stringify(parameters)).not.toMatch(/Explanation|abc|tip\.png|Definition|futureParameter|child-uuid/);
    },
  );

  it.each([
    ['<p>Hello <strong>world</strong>.</p>', 'Hello world.'],
    ['<p><em>A <strong>nested <span>word</span></strong></em>.</p>', 'A nested word.'],
    ['<p><a href="https://example.com/path" title="Hidden">Visible link</a></p>', 'Visible link'],
    ['<h2>Heading</h2><p>First<br>Second<br/>Third</p><p>Last</p>', 'Heading\nFirst\nSecond\nThird\nLast'],
    ['<p>A<br><br>B</p>', 'A\n\nB'],
    ['<ul><li>One</li><li><strong>Two</strong><ul><li>Nested</li></ul></li></ul>', 'One\nTwo\nNested'],
    ['<ol><li>First</li><li>Second</li></ol>', 'First\nSecond'],
    ['<table><tr><td>A<td>B<tr><td>C<td>D</table>', 'A\tB\nC\tD'],
    ['<table><caption>Caption</caption><tr><th>A</th><th>B</th></tr>' +
      '<tr><td>One</td><td><em>Two</em></td></tr></table>', 'Caption\nA\tB\nOne\tTwo'],
    ['<p>A &amp; B &lt; C &gt; D &quot;q&quot; &apos;s&apos;&nbsp;end</p>', 'A & B < C > D "q" \'s\' end'],
    ['<p>&eacute; &copy; &NotEqualTilde; &CounterClockwiseContourIntegral;</p>', 'é © ≂̸ ∳'],
    ['<p>&#65; &#xE9; &#X1F600; &#128; &#0; &#xD800; &#1114112;</p>', 'A é 😀 € � � �'],
    ['<p>&amp;amp; &lt;strong&gt; &unknown; &copy</p>', '&amp; <strong> &unknown; ©'],
    ['<p>A\n   B\t C</p>\n<p>D</p>', 'A B C\nD'],
    ['<pre>A  B\nC</pre>', 'A  B\nC'],
    ['<P>One<BR>Two<p>Three <b>bold', 'One\nTwo\nThree bold'],
    ['<p>Left <span title="a > b and <em>hidden</em>">word</span> right</p>', 'Left word right'],
    ['<p>Before<!-- hidden --><script>if (a < b) alert("Hidden")</script>' +
      '<style>.x { color: red; }</style><template>Hidden</template>' +
      '<img src="tip.png" alt="Hidden">After</p>', 'BeforeAfter'],
    ['<p>2 < 3 &amp; 5 > 4</p>', '2 < 3 & 5 > 4'],
    ['<p>Visible</p><span title="unfinished', 'Visible'],
    ['', ''],
    ['<p><br></p>', ''],
    ['   &nbsp; <p></p>', ''],
  ])('extracts readable visible PapiJo body text from %s', (html, expected) => {
    expect(convertPapiJo(html)).toBe(expected);
  });

  it('migrates mixed hidden descriptions before the ordinary HTML editor can stringify objects', () => {
    const parameters = {
      showTitleSlide: false, titleSlide: { description: legacy('H5P.AdvancedText 1.1', '<p>Title</p>') },
      timelineItems: ['text', 'image', 'none'].map((mode) => ({
        TextOrImage: mode, description: { ...legacy('H5P.AdvancedTextPapiJo 1.2'), params: {
          text: '<span data-papijo-tooltip="Explanation" data-papijo-tooltip-id="id">Visible</span>',
          tooltipImages: [{ id: 'id', image: { path: 'tip.png' } }], extra: {},
        } },
      })),
    };
    // The H5P HTML editor concatenates the incoming value into its input markup.
    expect(String(parameters.timelineItems[0].description)).toBe('[object Object]');
    const finished = jest.fn();
    loadUpgrade()(parameters, finished);
    expect(finished).toHaveBeenCalledWith(null, parameters);
    const descriptions = [parameters.titleSlide.description,
      ...parameters.timelineItems.map((slide) => slide.description)];
    expect(descriptions).toEqual(['<p>Title</p>', 'Visible', 'Visible', 'Visible']);
    descriptions.forEach((description) => {
      expect(typeof description).toBe('string');
      expect(String(description)).not.toContain('[object Object]');
    });
  });

  it('is idempotent and handles missing descriptions and missing text', () => {
    const parameters = { timelineItems: [
      {}, { description: '' }, { description: '<p>Already direct</p>' },
      { description: { library: 'H5P.AdvancedText 1.1', params: {} } },
      { description: { library: 'H5P.AdvancedTextPapiJo 1.2', params: { tooltipImages: [{}] } } },
    ] };
    const upgrade = loadUpgrade();
    const finished = jest.fn();
    upgrade(parameters, finished);
    expect(parameters.timelineItems.map((slide) => slide.description))
      .toEqual([undefined, '', '<p>Already direct</p>', '', '']);
    const once = JSON.stringify(parameters);
    upgrade(parameters, finished);
    expect(JSON.stringify(parameters)).toBe(once);
    expect(finished).toHaveBeenNthCalledWith(2, null, parameters);
    const missing = {};
    upgrade(missing, finished);
    expect(finished).toHaveBeenLastCalledWith(null, missing);
  });

  it.each([null, {}, [], { library: 'H5P.AdvancedText 1.1', params: [] },
    { library: 'H5P.Other 1.0', params: { text: 'Unknown' } },
    { library: 'H5P.AdvancedText 1.1' },
    { library: 'H5P.AdvancedTextPapiJo 1.2', params: { text: {} } },
    { library: 'H5P.AdvancedTextPapiJo 1.2', params: { text: 123 } },
    { library: 'H5P.AdvancedText 1.1', params: { text: 'Text', unknown: {} } },
  ])('retains ALL descriptions atomically for a malformed/unknown final description: %s', (description) => {
    const parameters = {
      titleSlide: { description: legacy('H5P.AdvancedText 1.1') },
      timelineItems: [
        { description: legacy('H5P.AdvancedTextPapiJo 1.2') },
        { description, TextOrImage: 'none' },
      ],
    };
    const original = JSON.stringify(parameters);
    const finished = jest.fn();
    loadUpgrade()(parameters, finished);
    expect(finished).toHaveBeenCalledTimes(1);
    expect(finished.mock.calls[0][0]).toMatchObject({ type: 'errorParamsBroken' });
    expect(finished.mock.calls[0][0].message).toContain('timelineItems[1].description');
    expect(finished.mock.calls[0]).toHaveLength(1);
    expect(JSON.stringify(parameters)).toBe(original);
  });

  it.each([null, [], { timelineItems: {} }])('rejects a malformed root without mutation: %s', (parameters) => {
    const original = JSON.stringify(parameters);
    const finished = jest.fn();
    loadUpgrade()(parameters, finished);
    expect(finished.mock.calls[0][0]).toMatchObject({ type: 'errorParamsBroken' });
    expect(JSON.stringify(parameters)).toBe(original);
  });
});
